# docker-compose.yml
version: '3.1'
services:
  blog_db:
    image: postgres
    volumes:
       - ./postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=123456
