# docker-compose.yml
version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - TZ=Asia/shanghai
      - PGTZ=Asia/shanghai
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
